### ISSUE TITLE
Add individual video links

### ISSUE THREAD

**Issue by rex4539** [adityapk00/zqw-docs#20]
Checking Transactions
https://youtu.be/5bSlX-CIeTA

Export Private Keys
https://youtu.be/0n2AFiTW8fs

Export Transactions
https://youtu.be/DACo9cDTcr0

Import Private Key
https://youtu.be/MbhdoTI4zSw

Labels
https://youtu.be/wd7HY9EZPiY

Memos
https://youtu.be/2ztL3W_ZVw0

Post to z-board.net
https://youtu.be/mYJOgSIrQik

Receive Transaction
https://youtu.be/fTYez8bFQsA

Send Transaction
https://youtu.be/iJxqmRW9ncg

Verify Node Synchronization
https://youtu.be/_DxED471wGQ

**Comment by garethtdavies** [comment]
Added via a couple of commits as a dedicated page and also links within the using zec wallet section
